name: Test Actions locally

on: [workflow_dispatch]

jobs:
  check-files: # Check the files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: GuillaumeFalourd/assert-command-line-output@v3
        with:
          command_line: cat tests/test1.txt
          contains: MathieuSoysal/file-updater-for-release@v1.0.0

      - uses: GuillaumeFalourd/assert-command-line-output@v3
        with:
          command_line: cat tests/test2.txt
          contains: MathieuSoysal/file-updater-for-release@v1.0.0

      - uses: GuillaumeFalourd/assert-command-line-output@v3
        with:
          command_line: cat tests/test-maven.txt
          contains: cloud.tools:jib-maven-plugin:3.2.1

  test-for-github-workflow: # Test the action with the GitHub workflow
    name: Test update dependency
    needs: check-files
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update files
        uses: ./
        with:
          files: tests/test1.txt tests/test2.txt
          github_repository: MathieuSoysal/file-updater-for-release
          prefix: MathieuSoysal/file-updater-for-release@

      - name: Test if file 1 have been updated
        uses: GuillaumeFalourd/assert-command-line-output@v3
        with:
          command_line: cat tests/test1.txt
          contains: MathieuSoysal/file-updater-for-release@v1.0.3

      - name: Test if file 2 have been updated
        uses: GuillaumeFalourd/assert-command-line-output@v3
        with:
          command_line: cat tests/test2.txt
          contains: MathieuSoysal/file-updater-for-release@v1.0.3



    # Test with a specific kind tag

      - name: Test kind of tag
        uses: ./
        with:
          files: tests/test-maven.txt
          github_repository: GoogleContainerTools/jib
          prefix: "cloud.tools:jib-maven-plugin:"
          suffix: ":build ."
          regex: "[0-9.]*"
          selector: maven

      - name: Test if file has been updated
        uses: GuillaumeFalourd/assert-command-line-output@v3
        with:
          command_line: cat tests/test-maven.txt
          contains: cloud.tools:jib-maven-plugin:3.2.1
          expected_result: FAILED